import { environment} from "src/environments/environment";


export const baseUrl= environment.production ? 'https://api.store.com': 'http://localhost/store'
export const productUrl =baseUrl + '/featuredprod.php'
export const cartUrl= 'http://localhost:3000'+'/cart'
export const registerUrl=baseUrl+'/insert.php'
export const wishlistUrl='http://localhost:3000' +'/wishList'
export const myAccountUrl=baseUrl +'/myaccount'
export const tshirtUrl=baseUrl +'/tshirt.php'
export const jeanUrl=baseUrl +'/jean.php'
export const phcaseUrl=baseUrl +'/phoneCases.php'
export const glassUrl=baseUrl +'/glass.php'
export const toteUrl=baseUrl +'/tote.php'
export const dsUrl=baseUrl +'/ds.php'
export const jjkUrl=baseUrl +'/jjk.php'
export const nanaUrl=baseUrl +'/nana.php'
export const narutoUrl=baseUrl +'/naruto.php'
export const aotUrl=baseUrl +'/aot.php'
export const otherUrl=baseUrl +'/other.php'
export const loginUrl=baseUrl +'/login.php'
export const allproductUrl=baseUrl +'/allproduct.php'
export const allprodUrl=baseUrl +'/displ.php'
export const addProdUrl=baseUrl +'/addproduct.php'
export const delProdUrl=baseUrl +'/delete.php?id='
export const updateProdUrl=baseUrl +'/update.php'
export const userUrl=baseUrl +'/users.php'
export const delUserUrl=baseUrl +'/deleteUser.php?id='
export const addUserUrl=baseUrl +'/addUser.php'
export const AdminUrl=baseUrl +'/admin.php'
export const getbyIdUrl=baseUrl +'/getbyId.php?id='
export const getUserByIdUrl=baseUrl +'/getUserById.php?id='
export const updateUserUrl=baseUrl +'/updateuser.php'


